# Generated by Django 4.2.13 on 2024-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
