# Generated by Django 4.2.13 on 2024-07-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookha', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Which_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookha.book'),
        ),
    ]
