# Generated by Django 4.2.13 on 2024-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookha', '0004_alter_comment_which_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='recc',
            field=models.BooleanField(default=True),
        ),
    ]
